kind: Service
apiVersion: v1
metadata:
  name: artifact-svc
  labels:
    app: artifact
spec:
  type: NodePort
  selector:
    app: artifact
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: artifact-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact
  template:
    metadata:
      labels:
        app: artifact
        version: v1
    spec:
      containers:
      - name: artifact-server
        image: artifact-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
